name: Generate Podcast Feeds

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      # 4. Run the feed generator
      - name: Run Feed Generator
        run: python feed.py

      # 5. Commit and push the updated podcast.xml
      - name: Push Updated Podcast Feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add podcast.xml
          git commit -m "Auto-update podcast feed" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
